# 
name: BuildGEMOC

on:  
  push: 

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      containerUID: ${{ steps.get-user.outputs.containerUID }}
      containerGID: ${{ steps.get-user.outputs.containerGID }}
    steps:
      - id: get-user
        run: echo "::set-output name=containerUID::`id -u`"
      - id: get-group
        run: echo "::set-output name=containerGID::`id -g`"   
 

  tycho-build2:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: gemoc/gemoc-builder:latest
      options: --env UID=${{ needs.configure.outputs.containerUID }} --env GID=${{ needs.configure.outputs.containerGID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Show context
        run: |
          id -u
          id -g
          echo $HOME
          ls -lsa $HOME
          echo ${{ github.workspace }}
          ls -lsa ${{ github.workspace }}
          ls -lsa /home/ubuntu/src
      - name: tycho linux_no_system_test build
        run: |
          ./tycho_build.sh linux_no_system_test         
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.17.0
        if: always()  # always run even if the previous step fails
        with:
          junit_files: "**/target/surefire-reports/TEST-*.xml"            
