# 
name: BuildStudio

on:  
  push: 
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/20 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-protocols:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Show context
        run: |
          id -u
          id -g
          echo $HOME
          ls -lsa $HOME
          echo ${{ github.workspace }}
          ls -lsa ${{ github.workspace }}
      - name: Set UID GID env
        run: |
          echo "RUNNER_UID=$(id -u)" >> $GITHUB_ENV
          echo "RUNNER_GID=$(id -G)" >> $GITHUB_ENV
      - name: Generate protocol in container
        uses: addnab/docker-run-action@v3
        with:
          image: gemoc/gemoc-builder:latest
          # -v $PWD/../../../..:/home/ubuntu/src -v $PWD/cache-m2:/home/ubuntu/.m2 --env UID=$(id -u) --env GID=$(id -g)
          options: -v ${{ github.workspace }}:/home/ubuntu/src --env UID=${{ env.RUNNER_UID }} --env GID=${{ env.RUNNER_GID }}
          run: |
            echo "This step is using a Public Docker Container Action "
            ./generate_protocols.sh
      - name: pomfirst build
        uses: addnab/docker-run-action@v3
        with:
          image: gemoc/gemoc-builder:latest
          # -v $PWD/../../../..:/home/ubuntu/src -v $PWD/cache-m2:/home/ubuntu/.m2 --env UID=$(id -u) --env GID=$(id -g)
          options: -v ${{ github.workspace }}:/home/ubuntu/src --env UID=${{ env.RUNNER_UID }} --env GID=${{ env.RUNNER_GID }}
          run: |
            echo "This step is using a Public Docker Container Action "
            ./pomfirst_build.sh
            
            
            